name: "Increment Version"
description: "Increment semantic version and create a new tag"

inputs:
  create-tag:
    description: "Create a tag with the new version"
    type: boolean
    required: false
    default: true

outputs:
  current-version:
    description: "The current version"
    value: ${{ steps.version.outputs.current-version }}
  version:
    description: "The new version"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        scheme: conventional_commits

    - name: Create tag
      uses: automas-dev/reusable-workflows/create_tag@main
      if: "inputs.create-tag"
      with:
        tag: ${{ steps.version.outputs.version }}
