name: Increment Version
description: Increment semantic version and create a new tag

inputs:
  dry-run:
    description: >
      Skip tag creation and only output new version,
      useful for steps that require the new version but run before tag creation
    type: boolean
    required: false
    default: false
  tag:
    description: Explicit tag value to use instead of generating a new value
    required: false
  create-aliases:
    description: Create / update alias tags for major and minor versions
    type: boolean
    required: false
    default: false

outputs:
  current-version:
    description: The current version
    value: ${{ inputs.tag || steps.version.outputs.current-version }}
  version:
    description: The new version
    value: ${{ inputs.tag || steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - if: ${{ inputs.tag }}
      shell: bash
      run: echo tag
    - if: ${{ !inputs.tag }}
      shell: bash
      run: echo not tag
    - if: ${{ inputs.tag == '' }}
      shell: bash
      run: echo tag eq empty
    - if: ${{ !inputs.tag != '' }}
      shell: bash
      run: echo not tag not eq empty

    # - name: Get next version
    #   uses: reecetech/version-increment@2024.10.1
    #   if: ${{ !inputs.tag }}
    #   id: version
    #   with:
    #     scheme: conventional_commits

    # - name: Create Version Tag
    #   uses: actions/github-script@v9
    #   # IDK WHY INPUT EVALUATES TO STRING INSTEAD OF BOOL
    #   if: ${{ inputs.dry-run != 'true' }}
    #   env:
    #     VERSION: ${{ inputs.tag || steps.version.outputs.version }}
    #   with:
    #     script: |
    #       const version = process.env.VERSION;
    #       console.log(`Got version ${version}`);

    #       github.rest.git.createRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: `refs/tags/${version}`,
    #         sha: context.sha
    #       }).catch(err => {
    #         if (context.ref === 'refs/heads/main') throw err;
    #         console.log(`Skipping creation of existing tag ${version}`);
    #       });

    # - name: Create Major / Minor Alias Tags
    #   uses: actions/github-script@v9
    #   if: ${{inputs.dry-run != 'true' &&  inputs.create-aliases == 'true' }}
    #   env:
    #     VERSION: ${{ inputs.tag || steps.version.outputs.version }}
    #   with:
    #     script: |
    #       const version = process.env.VERSION;
    #       console.log(`Got version ${version}`);

    #       if (!/([0-9]+\.){2}/.test(version)) {
    #         throw new Error(`Invalid version ${version}`);
    #       }
    #       const [major, minor] = version.split('.', 2);
    #       console.log({major, minor});

    #       // Major version
    #       github.rest.git.createRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: `refs/tags/v${major}`,
    #         sha: context.sha
    #       }).catch(err => {
    #         if (err.status !== 422) throw err;
    #         github.rest.git.updateRef({
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           // Note: without /ref/
    #           ref: `tags/v${major}`,
    #           sha: context.sha
    #         });
    #       });

    #       // Major.Minor version
    #       github.rest.git.createRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: `refs/tags/v${major}.${minor}`,
    #         sha: context.sha
    #       }).catch(err => {
    #         if (err.status !== 422) throw err;
    #         github.rest.git.updateRef({
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           // Note: without /ref/
    #           ref: `tags/v${major}.${minor}`,
    #           sha: context.sha
    #         });
    #       });
