name: ci

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install YAML Lint
        run: pip install yamllint

      - name: Run YAML Lint
        run: yamllint -c yamllint.yml .

  increment_version:
    name: Increment Version
    uses: ./.github/workflows/increment_version.yml
    secrets: inherit
    with:
      dry-run: ${{ github.ref != 'refs/heads/main' || contains(github.event.head_commit.message, 'NO RELEASE') }}
      aliases: true
      prefix: v
      enforce_conventional_commit: true

    # needs: [lint]

    permissions:
      contents: write

  check:
    runs-on: ubuntu-latest
    if: always()

    needs: [lint, increment_version]

    timeout-minutes: 1

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
