on:
  push:

jobs:
  test_inc_ver_workflow:
    uses: twh2898/reusable-workflows/.github/workflows/increment_version.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit

  test_inc_ver_action:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      current-version: ${{ steps.version.outputs.current-version }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: twh2898/reusable-workflows/increment_version@main
