on:
  workflow_call:

jobs:
  tmp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Export TF_VAR vars
        uses: actions/github-script@v8.0.0
        env:
          ALL_VARS: ${{ toJSON(vars) }}
        with:
          script: |
            const vars = JSON.parse(process.env.ALL_VARS);
            for (const [key, value] of Object.entries(vars)) {
              if (key.startsWith('TF_VAR_')) {
                const exportKey = `TF_VAR_${key.slice('TF_VAR_'.length).toLowerCase()}`;
                core.exportVariable(exportKey, value);
                core.info(`Exported: ${key} as ${exportKey}`);
              }
            }

      - name: Export TF_VAR secrets
        uses: actions/github-script@v8.0.0
        env:
          ALL_SECRETS: ${{ toJSON(secrets) }}
        with:
          script: |
            const secrets = JSON.parse(process.env.ALL_SECRETS);
            for (const [key, value] of Object.entries(secrets)) {
              if (key.startsWith('TF_VAR_')) {
                const exportKey = `TF_VAR_${key.slice('TF_VAR_'.length).toLowerCase()}`;
                core.exportVariable(exportKey, value);
                core.info(`Exported: ${key} as ${exportKey}`);
              }
            }

      - run: echo env got $TF_VAR_foo
      - run: echo env got $TF_VAR_bar
