name: test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  increment_version:
    name: Increment Version
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: conventional_commits

      - name: Create tag
        uses: automas-dev/reusable-workflows/create_tag@dispatch
        with:
          tag: ${{ steps.version.outputs.version }}
          create-aliases: true
